version: '3'

tasks:
  lint:
    desc: Run linters using golangci-lint
    cmds:
      - golangci-lint run --config .golangci.yml
    silent: true
  clear:
    cmds:
      - mkdir -p ./.runtime
      - rm -f ./.runtime/*
    silent: true
  test:
    deps: [clear]
    cmds:
      - go test -cover ./... > ./.runtime/test.log
      - go test -race ./... >> ./.runtime/test.log
    silent: true
  build:
    deps: [lint, clear, test]
    cmds:
      - go build -o ./.runtime/example ./cmd/example/*.go
    silent: true
  run:
    deps: [build]
    cmds:
      - ./.runtime/example -env=development -lt=2s
    silent: true
  run-dev:
    cmds:
      - docker-compose -f ./deployments/development/docker-compose.yaml up -d --build
  stop-dev:
    cmds:
      - docker-compose -f ./deployments/development/docker-compose.yaml down --remove-orphans
      - docker volume prune --force
      - docker volume rm dev-store --force